### ISSUE TITLE
Attempting to pass through coral USB

### ISSUE THREAD

**Issue by marleyjaffe** [remz1337/Proxmox#14]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Using your frigate script for the nvidia drivers, however I am having issues getting my Coral USB to pass through. I have USB pass through working with an old tteck based container, and I believe this is because your container (unlike the original tteck script) is setup as privileged instead of unprivileged. 

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 11

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

error log entry: `frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.`

The permissions on the USB indicate its a privileged container issue as I dealt with the same thing to get CIFS to mount properly.
```
root@frigate:~# ls -laih /dev/bus/usb/
total 0
  9 drwxr-xr-x 3 root   root    60 Nov  7 02:11 .
  8 drwxr-xr-x 3 root   root    60 Nov  7 02:11 ..
327 drwxr-xr-x 2 nobody nogroup 80 Nov  3 14:28 002
```

**Comment by marleyjaffe** [comment]
lxc config:
```
arch: amd64
cores: 8
features: nesting=1
hostname: frigate
memory: 16384
mp0: /mnt/pve/cctv_media/,mp=/media/frigate
net0: name=eth0,bridge=vmbr0,gw=192.168.1.1,hwaddr=BC:24:11:2D:64:4E,ip=dhcp,type=veth
onboot: 1
ostype: debian
rootfs: ssd_storage:subvol-107-disk-0,size=40G
swap: 1024
tags: proxmox-helper-scripts
unprivileged: 1
lxc.cgroup2.devices.allow: c 189:* rwm
lxc.cgroup2.devices.allow: c 195:* rwm
lxc.cgroup2.devices.allow: c 234:* rwm
lxc.cgroup2.devices.allow: c 236:* rwm
lxc.cgroup2.devices.allow: c 237:* rwm
lxc.cgroup2.devices.allow: c 226:* rwm
lxc.cap.drop:
lxc.mount.auto: proc:rw sys:rw
lxc.mount.entry: /dev/nvidia0 dev/nvidia0 none bind,optional,create=file
lxc.mount.entry: /dev/nvidiactl dev/nvidiactl none bind,optional,create=file
lxc.mount.entry: /dev/nvidia-uvm dev/nvidia-uvm none bind,optional,create=file
lxc.mount.entry: /dev/nvidia-uvm-tools dev/nvidia-uvm-tools none bind,optional,create=file
lxc.mount.entry: /dev/dri dev/dri none bind,optional,create=dir
# lxc.mount.entry: /dev/bus/usb/002 dev/bus/usb/002 none bind,optional,create=dir
lxc.mount.entry: /dev/bus/usb dev/bus/usb none bind,optional,create=dir
```

**Comment by remz1337** [comment]
Indeed, I do not allow any privileged containers in my fork. However, you can manually override this by simply changing the `unprivileged` attribute in your config to `0` ;)
