### ISSUE TITLE
colour command not found 

### ISSUE THREAD

**Issue by yousaf465** [remz1337/Proxmox#15]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When I try to run this script it throws this error
``` \Customizing LXC creation
 ✓ Rebooted LXC
 |/bin/bash: line 1: color: command not found
```

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/user-attachments/assets/31ca3754-ea30-4e54-8e45-4b255b9163cc)

**Comment by remz1337** [comment]
Please try again with the new repo: https://github.com/remz1337/ProxmoxVE.
 This one is deprecated.
